### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Voga25n** [IceroDev/NetBot#4]
Bonjour,
L'envoie des status ne marche pas ; sur la console l'erreur affiché ` TypeError: Cannot read property 'send' of undefined
`

**Comment by IceroDev** [comment]
Bonjour Voga25n,

Cette erreur n'est pas due au code du bot mais bien à la mauvaise configuration du bot de votre côté.

Je rappelle que le code de NetBot est sur github pour que des personnes expérimentées en discord.js puissent prendre les fonctionnalités qui les intéressent. Pas pour lancer un bot sur base de ce code uniquement.

Codialement,
Jean
